#ifndef __Bkgtrack_H__
#define __Bkgtrack_H__ 1
//std
#include <vector>
#include <string>
#include <map>
#include <array>
#include <exception>
#include <cmath>
#include <algorithm>
#include <numeric>

//ROOT CERN
#include "TString.h"
#include "TFile.h"
#include "TTree.h"
#include "TCanvas.h"
#include "TH2D.h"
#include "TH1D.h"
#include "TH1F.h"
#include "Lansxlogon.h"

//pars of TPC sensitive gas region
constexpr double _TPCR0 = 635.; // [mm]
constexpr double _TPCR1 = 1750.; // [mm]
constexpr double _TPCZ0 = -2750.; // [mm]
constexpr double _TPCZ1 = -_TPCZ0;

const std::array<std::string, 5> _ProcName {"initStep","Transportation","compt","phot","conv"};

struct tracks_eeg
{
    int pdg;
    int parentid;
    std::vector<float> vxp;
    std::vector<float> vyp;
    std::vector<float> vzp;
    std::vector<float> vde;
};

class Bkgtrack
{
public:
    Bkgtrack(TString tracksfile);
    ~Bkgtrack();

    //public methods
    void PrintTrackInfo(int numofentries=1);
    
    //Plot some histograms
    TCanvas* PlotPositionXYZDistribution(int pdg = 22, int plane=0, bool Isstart=true);
    TCanvas* PlotGammaKEDistribution();
    
    void FillMapstracks();
    const std::map<int, std::vector<tracks_eeg>>& GetTrackMaps() { return fMaptracks; };

protected:
    void InitialPars();
    std::vector<size_t> CrossTPCIdx();

private:
    TFile* f_Tf;
    TTree* f_Tr;
    int fTrkid, fParentid, fPDG;

    std::vector<float>* fStepx, * fStepy, * fStepz, * fStepkE, * fStepde;
    std::vector<std::string>* fStepproc;
    std::map<int, std::vector<tracks_eeg>> fMaptracks; // key -> track_id
                                                      // value -> vector<tracks_eeg>, first element -> gamma track
                                                      //                              other -> e+/e- tracks generated by gamma through compt phot conv
    TH1D* hKineticE0, *hKineticE1, *hKineticE2, *hKineticE3;
};


#endif
