#ifndef __Bkgtrack_H__
#define __Bkgtrack_H__ 1
//std
#include <vector>
#include <string>
#include <map>
#include <array>
#include <exception>
#include <cmath>
#include <algorithm>
#include <numeric>
#include <list>
#include <iterator>
#include <tuple>

//ROOT CERN
#include "TString.h"
#include "TFile.h"
#include "TTree.h"
#include "TCanvas.h"
#include "TH2D.h"
#include "TH1D.h"
#include "TH1F.h"
#include "Lansxlogon.h"

//pars of TPC sensitive gas region
constexpr double _TPCR0 = 635.; // [mm]
constexpr double _TPCR1 = 1750.; // [mm]
constexpr double _TPCZ0 = -2750.; // [mm]
constexpr double _TPCZ1 = -_TPCZ0;// [mm]

const std::array<std::string, 6> _ProcName {"initStep","Transportation","compt","phot","conv","Rayl"};

struct tracks_eeg
{
    int pdg;
    int parentid;
    int trkid;
    float e0;
    std::vector<float> vxp;
    std::vector<float> vyp;
    std::vector<float> vzp;
    std::vector<float> vde;
};

class Bkgtrack
{
public:
    Bkgtrack(TString tracksfile);
    ~Bkgtrack();

    //=============================================================================================
    //Public methods
    //=============================================================================================
    
    // Print Track Info from .root
    void PrintTrackInfo(int numofentries=1);
    
    // Check point (xx,yy,zz) in TPC region
    bool IsinTPCgasRegion(float xx, float yy, float zz);
    
    // Plot some histograms
    TCanvas* PlotPositionXYZDistribution(int pdg = 22, int plane=0, bool Isstart=true);
    
    // Get Particle type distribution, all particle types that cross TPC
    // TODO: only three type (e+ e- gamma) of particles in .root file, need to update LogAna.cpp 
    TCanvas* PlotParticleType();
     
    //=============================================================================================
    //Two functions for plotting gammas energy and position distribution
    //=============================================================================================
    //+ PlotGammaKEDistribution(), plot gammas energy that just cross TPC region (stepid==0), 
    //                                  gammas energy that interact with gas (stepid==0),
    //                                  gammas energy that interact with gas (first step in TPC region)
    //                                  gammas energy that stepid==0 && (x,y,z)_0 in TPC region
    TCanvas* PlotGammaKEDistribution();

    //+ PlotGammaPositionDistribution(), plot Gamma position z and initial kE v.s. pos z distribution
    //                                   (gamma cross and interact with TPC gas or all gammas cross TPC) 
    TCanvas* PlotGammaPositionDistribution(bool IsAll = false);

    //+ PlotGammaDirectrionDistribution(), plot Gamma (cross and interact with TPC gas or all gammas cross TPC) 
    //                                     cos(theta) v.s. pos z at start point 
    TCanvas* PlotGammaDirectionDistribution(bool IsAll = false);
    
    // Get all Energy deposit by those secondary e-, generated by those gammas interacting with TPC gas
    float GetEDepbyelectronInTPC(int BX=10);

    // Fill e+, e- and gamma tracks map. 
    // Those gammas interact with gas will be filled into `fMaptracks`, key -> gamma track id
    //                                                                  value:  list[0] -> its parent particle
    //                                                                          list[1] -> gamma tracks
    //                                                                          list[2] list[3]... -> its daughter particles
    void FilleegtrackMap();

    // Get 

    // Get private track map `fMaptracks`
    const std::map<int, std::list<tracks_eeg>>& GeteegTrackMaps() { return fMaptracks; };
    
    // Get primary particle maps, return std::map<int, std::list<tracks_eeg>> map, parent_id==0
    //                                                                        key -> track id
    //                                                                        value: list[0] list[1] ... -> all primary particles
    const std::map<int, std::list<tracks_eeg>> GetPrimaryParticleMaps();

protected:
    void InitialPars();
    std::vector<size_t> CrossTPCIdx();

private:
    TFile* f_Tf;
    TTree* f_Tr;
    
    // vars for reading Tree 
    int fTrkid, fParentid, fPDG;
    std::vector<float>* fStepx, * fStepy, * fStepz, * fStepkE, * fStepde;
    std::vector<std::string>* fStepproc;

    std::map<int, std::list<tracks_eeg>> fMaptracks;  // key -> track_id
                                                      // value -> vector<tracks_eeg>, first element -> gamma track
                                                      //                              other -> e+/e- tracks generated by gamma through compt phot conv
    std::map<int, int> fMapParentTrkofGamma;          // key -> gamma track parentid
                                                      // value -> gamma track id
    TH1D* hKineticE0, *hKineticE1, *hKineticE2, *hKineticE3;
};


#endif
